import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Task from "../components/Task";
import Popup from "../components/Popup";
import { useState } from "react";
import TaskList from "../components/TaskList";
import PopupRemove from "../components/PopupRemove";

const tasks = [
  {
    title: "Jazmín",
  },
  {
    title: "Daniel",
  },
];


// Sets the submit task window as hidden.
export default function Home() {
  const [hidden, setHidden] = useState(true);
  const [hiddenRemove, setHiddenRemove] = useState(null);
  const onFormSubmit = (data) => {
    tasks.push(data);
  };

  var toDelete;

  const pointElement = (element) => {
    toDelete=element;
  };

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>ToDo App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>Your ToDo's</h1>

          <p className={styles.description}>Let's start by adding a task</p>
        </main>

        <div className={styles.forms}>
          <button
            onClick={() => setHidden(false)}
            id="btn-abrir-popup"
            className={styles["btn-abrir-popup"]}
          >
            Add new task
          </button>
        </div>

        <TaskList tasks={tasks} open={setHidden} close={setHiddenRemove}  point={pointElement}/>

        {!hidden && (
          <Popup
            onceSubmited={(data) => onFormSubmit(data)}
            close={setHidden}
          />
        )}

        {hiddenRemove!==null && (
          <PopupRemove
            close={setHiddenRemove}
            item={hiddenRemove}
            tasks={tasks}
          />
        )}
      </div>
    </>
  );
}
