import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Task from "../components/Task";
import Popup from "../components/Popup";
import { useState } from "react";
import TaskList from "../components/TaskList";

const tasks = [
  {
    title: "Jazmín",
  },
  {
    title: "Daniel",
  },
];

export default function Home() {
  const [hidden, setHidden] = useState(true);

  const onFormSubmit = (data) => {
    tasks.push(data);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>ToDo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>ToDo App</h1>

        <p className={styles.description}>Get started by adding your tasks.</p>
      </main>

      <div className={styles.forms}>
        <button
          onClick={() => setHidden(false)}
          id="btn-abrir-popup"
          className={styles["btn-abrir-popup"]}
        >
          Add new task
        </button>
      </div>

      <TaskList tasks={tasks} />

      {!hidden && (
        <Popup onceSubmited={(data) => onFormSubmit(data)} close={setHidden} />
      )}
    </div>
  );
}
